<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Shopbybrand
 */
 
$version = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\ProductMetadataInterface')->getVersion();
$isMage23 = (version_compare($version, '2.3.0', '>=') ||  version_compare($version, '2.3.0-dev', '>='));
$isMage244 = (version_compare($version, '2.4.4', '>=') ||  version_compare($version, '2.4.4-dev', '>='));
?>
<?php if ($isMage244) : ?>
<script>
require.config({
    map: {
        '*': {
            tinymce: 'tiny_mce_5/tinymce.min'
        }
    }
});
</script>
<?php elseif ($isMage23) : ?>
<script>
require.config({
    map: {
        '*': {
            tinymce: 'tiny_mce_4/tinymce.min'
        }
    }
});
</script>
<?php endif ?>
<?php
$mediaUrl = $this->helper('Magerubik\Shopbybrand\Helper\Wysiwyg\Images')->getBaseUrl();
$defaultThumbnail = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\View\Asset\Repository')->getUrl('Magerubik_Shopbybrand/images/placeholder_thumbnail.jpg');
?>
<script>
if (typeof Magerubik == 'undefined') {
    var Magerubik = {};
}
Magerubik.mediaUrl = '<?php echo $mediaUrl; ?>';
require(['jquery'], function($) {
require(['Magerubik_Shopbybrand/js/browser'], function() {
    var mediaUrl = Magerubik.mediaUrl;
    var defaultThumbnail = '<?php echo $defaultThumbnail ?>';
    window.changePreviewImage = function(obj) {
        var $_input = $(obj);
        if ($_input.parents('.admin__field-control').find('.attached_image img').length > 0) {
            var $_img = $_input.parents('.admin__field-control').find('.attached_image img').first();
            $_img.attr('src', mediaUrl + $_input.val());
        }
        $_input.prop('disabled', false);
    };
    window.clearValue = function(obj) {
        $_btn = $(obj);
        if ($_btn.parents('.admin__field-control').find('.input-image').length > 0) {
            var $_input = $_btn.parents('.admin__field-control').find('.input-image').first();
            $_input.val('');
        }
        if ($_btn.parents('.admin__field-control').find('.attached_image img').length > 0) {
            var $_img = $_btn.parents('.admin__field-control').find('.attached_image img').first();
            $_img.attr('src', defaultThumbnail);
        }
    }
});
});
</script>