<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Shopbybrand
 * @var $block Magerubik\Shopbybrand\Block\Brand\BrandInformation
 */ ?>
 
<?php
$brand = $this->getBrand();
$displayCover = $brand->getBrandCover();
$displayThumbnail = $brand->getBrandThumbnail();
if ($brandDesc = $brand->getBrandDescription()) {
    $brandDesc = $this->helper('Magerubik\Shopbybrand\Helper\Data')->htmlFilter($brandDesc);
}
$displayDescription = $brandDesc;
$brand->setThumbnail($this->getThumbnailImage($brand, ['width' => 250]));
?>
<?php if ($displayCover || $displayThumbnail || $displayDescription) : ?>
<div class="brand-container" itemscope itemtype="http://schema.org/brand">
    <div class="block-content">
        <?php if (!($displayCover || $displayThumbnail)) : ?>
            <div class="row thumb-desc-section">
                <div class="col-md-12">
                    <div class="brand-desc" itemprop="description"><?php echo $brandDesc ?></div>
                </div>
            </div>
        <?php elseif ($displayThumbnail && !$displayCover) : ?>
        <div class="row thumb-desc-section">
        	<div class="col-4 col-md-2">
            	<div class="brand-img-wrap">
                    <img class="brand-image" itemprop="image" src="<?php echo $brand->getThumbnail(); ?>" />
                </div>
            </div>
            <div class="col-8 col-md-10">
            	<div class="brand-desc" itemprop="description"><?php echo $brandDesc ?></div>
            </div>
        </div>
		<?php elseif ($displayCover) : ?>
        <?php
            $socialButtonsHtml = $this->getLayout()->createBlock('Magento\Framework\View\Element\Template', 'brand_page_share')
                ->setBrand($brand)
                ->setTemplate('Magerubik_Shopbybrand::brand/social_buttons.phtml')
                ->toHtml();
        ?>
        <div class="cover-section">
			<div class="cover-wrap">
				<img class="brand-cover" src="<?php echo $this->getCoverImage($brand, ['width' => 1200]); ?>" />
			</div>
            <div class="after-cover">
                <div class="row">
                    <?php if ($displayThumbnail) : ?>
                    <div class="col-4 col-md-2 thumb-section">
                        <div class="brand-img-wrap">
                            <img class="brand-image" itemprop="image" src="<?php echo $brand->getThumbnail(); ?>" />
                        </div>
                    </div>
                    <?php endif ?>
                    <div class="social-section <?= $displayThumbnail?'col-8 col-md-10':'col-md-12' ?>">
                        <strong class="title hidden-xs"><?= $brand->getBrandLabel(); ?></strong>
                        <?php echo $socialButtonsHtml ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row desc-section">
			<div class="col-md-12">
            	<div class="brand-desc" itemprop="description"><?php echo $brandDesc ?></div>
            </div>
        </div>
		<?php endif ?>
    </div>
</div>
<?php endif ?>