<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Shopbybrand
 * @var $block Magerubik\Shopbybrand\Block\Brand\BrandInformation
 */ ?>

<?php
$_brand = $this->getBrandOfCurrentProduct();
$block->setBrand($_brand);
$_brandUrl = $_brand->getUrl();
?>
<?php if ($_brand->getOptionId()) : ?>
<?php $label = $this->stripTags($_brand->getData('brand_label')); ?>
<div class="product-brand-info">
	<a class="brand-link" title="<?php echo $label; ?>" href="<?php echo $_brandUrl ?>">
        <img alt="<?php echo $label; ?>" class="brand-img zoom-eff" src="<?php echo $_brand->getThumbnail() ?>" />
    </a>
</div>
<?php endif ?>