<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Shopbybrand
 */
?>

<?php
$brand = $this->getBrand();
$url = urlencode($this->stripTags($brand->getUrl()));
$desc = urlencode($this->stripTags($brand->getData('brand_description')));
$image = urlencode($this->stripTags($brand->getThumbnail()));
$name = urlencode($this->stripTags($brand->getData('brand_label')));
?>

<ul class="hkk-social-listing">
    <li class="item">
        <button onclick='window.open("https://www.facebook.com/sharer/sharer.php?u=<?= $url; ?>","","menubar=1,resizable=1,width=700,height=600")' href="javascript:void(0)" class="share-btn" title="<?= __('Share on Facebook') ?>"><i class="fab fa-facebook-f"></i></button>
    </li>
    <li class="item">
        <button onclick='window.open("https://twitter.com/intent/tweet?url=<?= $url; ?>&text=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' target="_blank" rel="nofollow" href="javascript:void(0)" class="share-btn" title="<?= __('Share on Twitter') ?>"><i class="fab fa-twitter"></i></button>
    </li>
    <li class="item">
        <button onclick='window.open("https://www.linkedin.com/shareArticle?mini=true&url=<?= $url; ?>&title=<?= $name ?>&ro=false&summary=<?= $desc ?>&source=","","menubar=1,resizable=1,width=700,height=600")' title="<?= __('Share on LinkedIn') ?>" rel="nofollow" title="" href="javascript:void(0)" class="share-btn"><i class="fab fa-linkedin-in"></i></button>
    </li>
    <li class="item">
        <button onclick='window.open("https://plus.google.com/share?url=<?= $url; ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Share on Google+') ?>" href="javascript:void(0)" class="share-btn"><i class="fab fa-google-plus-g"></i></button>
    </li>
    <li class="item">
        <button onclick='window.open("https://www.pinterest.com/pin/create/button/?url=<?= $url; ?>&media=<?= $image ?>&description=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Share on Pinterest') ?>" href="javascript:void(0)" class="share-btn"><i class="fab fa-pinterest-p"></i></button>
    </li>
</ul>